import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// componentes
import Header from "./pages/Header";
import PageTransition from "./pages/PageTransition";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Ale. | Portfólio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-32.png",
    iconSizes: {
      "32x32": "/favicon-32x32.png",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <div>
          <Header />
          <PageTransition>{children}</PageTransition>
        </div>
      </body>
    </html>
  );
}
